#!/bin/bash

# Container-only proxy configuration script
# This script ONLY affects running containers, does NOT modify:
# - Docker daemon configuration
# - Docker client configuration  
# - Host system configuration

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored messages
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Default proxy configuration
PROXY_HOST=""
PROXY_PORT=""
PROXY_USER=""
PROXY_PASS=""
NO_PROXY="localhost,127.0.0.1,.corp"

# Get proxy configuration
get_proxy_config() {
    echo "Container Proxy Configuration (Host system will NOT be modified)"
    echo "================================================================="
    
    read -p "Proxy server address: " PROXY_HOST
    read -p "Proxy server port: " PROXY_PORT
    read -p "Username (optional, press Enter to skip): " PROXY_USER
    if [[ -n "$PROXY_USER" ]]; then
        read -s -p "Password: " PROXY_PASS
        echo ""
    fi
    read -p "No proxy addresses (default: localhost,127.0.0.1,.corp): " NO_PROXY_INPUT
    
    NO_PROXY=${NO_PROXY_INPUT:-"localhost,127.0.0.1,.corp"}
    
    # Build proxy URL
    if [[ -n "$PROXY_USER" && -n "$PROXY_PASS" ]]; then
        PROXY_URL="http://${PROXY_USER}:${PROXY_PASS}@${PROXY_HOST}:${PROXY_PORT}"
    else
        PROXY_URL="http://${PROXY_HOST}:${PROXY_PORT}"
    fi
    
    print_info "Proxy URL: $PROXY_URL"
    print_info "No proxy: $NO_PROXY"
}

# Create container proxy environment file
create_container_env_file() {
    local env_file="container-proxy.env"
    
    print_info "Creating container proxy environment file: $env_file"
    
    cat > "$env_file" << EOF
# Container proxy environment variables
# Generated by container-proxy-only.sh
HTTP_PROXY=$PROXY_URL
HTTPS_PROXY=$PROXY_URL
NO_PROXY=$NO_PROXY
http_proxy=$PROXY_URL
https_proxy=$PROXY_URL
no_proxy=$NO_PROXY
EOF
    
    print_success "Environment file created: $env_file"
    return 0
}

# Create proxy helper functions
create_helper_functions() {
    local helper_file="docker-proxy-helpers.sh"
    
    print_info "Creating Docker proxy helper functions: $helper_file"
    
    cat > "$helper_file" << 'EOF'
#!/bin/bash

# Docker container proxy helper functions
# Source this file: source docker-proxy-helpers.sh

# Set proxy environment variables for current session
set_container_proxy() {
    if [[ -f "container-proxy.env" ]]; then
        export $(cat container-proxy.env | grep -v '^#' | xargs)
        echo "Container proxy environment variables loaded"
    else
        echo "Error: container-proxy.env file not found"
        return 1
    fi
}

# Run container with proxy (using environment file)
docker_run_with_proxy() {
    if [[ -f "container-proxy.env" ]]; then
        docker run --env-file container-proxy.env "$@"
    else
        echo "Error: container-proxy.env file not found"
        return 1
    fi
}

# Run container with proxy (using -e parameters)
docker_run_proxy() {
    local proxy_url="$1"
    local no_proxy="${2:-localhost,127.0.0.1,.corp}"
    shift 2
    
    docker run \
        -e HTTP_PROXY="$proxy_url" \
        -e HTTPS_PROXY="$proxy_url" \
        -e NO_PROXY="$no_proxy" \
        -e http_proxy="$proxy_url" \
        -e https_proxy="$proxy_url" \
        -e no_proxy="$no_proxy" \
        "$@"
}

# Execute command in running container with proxy
docker_exec_with_proxy() {
    local container_name="$1"
    shift
    
    if [[ -f "container-proxy.env" ]]; then
        # Read proxy settings from file
        local http_proxy=$(grep "^HTTP_PROXY=" container-proxy.env | cut -d'=' -f2)
        local https_proxy=$(grep "^HTTPS_PROXY=" container-proxy.env | cut -d'=' -f2)
        local no_proxy=$(grep "^NO_PROXY=" container-proxy.env | cut -d'=' -f2)
        
        docker exec \
            -e HTTP_PROXY="$http_proxy" \
            -e HTTPS_PROXY="$https_proxy" \
            -e NO_PROXY="$no_proxy" \
            -e http_proxy="$http_proxy" \
            -e https_proxy="$https_proxy" \
            -e no_proxy="$no_proxy" \
            "$container_name" "$@"
    else
        echo "Error: container-proxy.env file not found"
        return 1
    fi
}

# Show current proxy configuration
show_container_proxy() {
    if [[ -f "container-proxy.env" ]]; then
        echo "Current container proxy configuration:"
        cat container-proxy.env
    else
        echo "No container proxy configuration found"
    fi
}

# Test proxy in container
test_container_proxy() {
    local test_image="${1:-alpine:latest}"
    
    echo "Testing container proxy with image: $test_image"
    
    if [[ -f "container-proxy.env" ]]; then
        docker run --rm --env-file container-proxy.env "$test_image" sh -c '
            echo "Proxy environment variables:"
            env | grep -i proxy
            echo ""
            echo "Testing network connectivity..."
            if command -v curl >/dev/null 2>&1; then
                curl -s --max-time 10 https://httpbin.org/ip || echo "curl test failed"
            elif command -v wget >/dev/null 2>&1; then
                wget -q --timeout=10 -O- https://httpbin.org/ip || echo "wget test failed"
            else
                echo "Neither curl nor wget available for testing"
            fi
        '
    else
        echo "Error: container-proxy.env file not found"
        return 1
    fi
}

# Usage examples
show_usage_examples() {
    cat << 'USAGE'

Container Proxy Helper Functions Usage:
======================================

1. Load helper functions:
   source docker-proxy-helpers.sh

2. Set proxy for current session:
   set_container_proxy

3. Run container with proxy (using env file):
   docker_run_with_proxy -it ubuntu:20.04 bash

4. Run container with proxy (direct):
   docker_run_proxy "http://proxy:8080" "localhost,127.0.0.1" -it ubuntu:20.04 bash

5. Execute command in running container with proxy:
   docker_exec_with_proxy my-container curl https://google.com

6. Test proxy configuration:
   test_container_proxy

7. Show current proxy config:
   show_container_proxy

USAGE
}

# Export functions if sourced
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    echo "Docker proxy helper functions loaded!"
    echo "Run 'show_usage_examples' to see usage examples"
fi
EOF
    
    chmod +x "$helper_file"
    print_success "Helper functions created: $helper_file"
}

# Create Docker Compose example
create_compose_example() {
    local compose_file="docker-compose-container-proxy.yml"
    
    print_info "Creating Docker Compose example: $compose_file"
    
    cat > "$compose_file" << EOF
version: '3.8'

# Docker Compose example with container-only proxy configuration
# This does NOT modify Docker daemon or host system settings

services:
  # Example web application with proxy
  webapp:
    image: nginx:alpine
    ports:
      - "8080:80"
    env_file:
      - container-proxy.env
    networks:
      - app-network

  # Example application that needs internet access
  curl-test:
    image: alpine:latest
    env_file:
      - container-proxy.env
    command: >
      sh -c "
        apk add --no-cache curl &&
        echo 'Testing proxy connection...' &&
        curl -s https://httpbin.org/ip &&
        tail -f /dev/null
      "
    networks:
      - app-network

  # Example Python application with proxy
  python-app:
    image: python:3.9-slim
    env_file:
      - container-proxy.env
    command: >
      bash -c "
        pip install requests &&
        python -c 'import requests; print(\"Proxy test:\", requests.get(\"https://httpbin.org/ip\").json())' &&
        tail -f /dev/null
      "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
EOF
    
    print_success "Docker Compose example created: $compose_file"
}

# Show usage instructions
show_usage() {
    cat << 'USAGE'

Container-Only Proxy Configuration Complete!
===========================================

Files created:
- container-proxy.env              : Environment variables for containers
- docker-proxy-helpers.sh          : Helper functions for easy usage
- docker-compose-container-proxy.yml : Docker Compose example

Quick Usage:
-----------

1. Use with docker run:
   docker run --env-file container-proxy.env -it ubuntu:20.04 bash

2. Use with Docker Compose:
   docker-compose -f docker-compose-container-proxy.yml up

3. Use helper functions:
   source docker-proxy-helpers.sh
   docker_run_with_proxy -it ubuntu:20.04 bash

4. Test proxy configuration:
   source docker-proxy-helpers.sh
   test_container_proxy

What this script does NOT modify:
--------------------------------
✗ Docker daemon configuration
✗ Docker client configuration
✗ Host system proxy settings
✗ System environment variables

What this script provides:
-------------------------
✓ Container environment variables only
✓ Easy-to-use helper functions
✓ Docker Compose examples
✓ Proxy testing utilities

USAGE
}

# Main function
main() {
    print_info "Container-Only Proxy Configuration"
    echo "===================================="
    print_warning "This script will NOT modify Docker daemon or host system settings"
    print_warning "It only creates files for container-level proxy configuration"
    echo ""
    
    get_proxy_config
    echo ""
    
    create_container_env_file
    create_helper_functions
    create_compose_example
    
    echo ""
    show_usage
}

# Run main function
main "$@"